name: Hello
on: push
jobs:
  hello:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ vars.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
    steps:
      - run: echo 'Hello, world'
      - uses: actions/checkout@v4
      - run: echo "${USERNAME}"
      - run: echo "${PASSWORD}"
      - run: echo "${PASSWORD:0:0} ${PASSWORD#?}"
